
# Server
HOST=0.0.0.0
PORT=1337

# Secrets
APP_KEYS=sDNNS6s4EfjGj8LYLoqI5g==,PA1LjhAJgRX4AJkeU2QpoA==,AydiVFkuov0NCn7Vugd2ZA==,N9wUtlUwCN49AAGrK0hM/Q==
API_TOKEN_SALT=OliDW+cMqaXIPrnyFKAZlQ==
ADMIN_JWT_SECRET=f0+FmH26L1h1bBznfR+Rfw==
TRANSFER_TOKEN_SALT=ZDv0fPcqcX4epFgYNOaXGA==

# Database
DATABASE_CLIENT=postgres
DATABASE_HOST=127.0.0.1
DATABASE_PORT=5432
DATABASE_NAME=strapi
DATABASE_USERNAME=root
DATABASE_PASSWORD=root
DATABASE_SSL=false
DATABASE_FILENAME=
